### PR TITLE
support multiple avoid type

### PR DESCRIPTION
**Pull request by liorsion**

### CODE REVIEW

**Comment by chiu0602** [comment]
change
`for (argIdx in argsArray)`
to
`for (var argIdx in argsArray)`
can avoid check fail

**Comment by fabriziomoscon** [comment]
It seems legittimate

**Comment by fabriziomoscon** [comment]
published as npm `googlemaps@1.12.0`

**Comment by liorsion** [comment]
thanks for the good job, hope I can help further.

**Comment by fabriziomoscon** [comment]
sure, I am not using this module in any of my active projects at the moment. So please feel free to open issues and PRs for anything you find

**Pull request merged**
