### PR TITLE
Bump `request` per security warning

### PR DESCRIPTION
**Pull request by kirkstrobeck**
- Request is now https://github.com/request/request/tree/v2.73.0
- Vulnerability https://nodesecurity.io/advisories/77
  Path: googlemaps@1.6.0 > request@2.44.0 > hawk@1.1.1

### CODE REVIEW

**Comment by fabriziomoscon** [comment]
Hi @kirkstrobeck thanks for contributing. Could you rebase your code in top of master and run the testa again?

**Comment by kirkstrobeck** [comment]
`master` is currently failing

**Comment by fabriziomoscon** [comment]
yes sorry my bad.
It should be fine again now

**Comment by fabriziomoscon** [comment]
I don't get what happened here. It seems that you merged master rather than rebase your branch in top of it. Maybe it would be faster to branch from the upstream/master and re-submit the PR.

**Comment by fabriziomoscon** [comment]
published as npm `googlemaps@1.12.0`

**Pull request closed without merging**
