### PR TITLE
Enable multiple style parameters in query string.

### PR DESCRIPTION
**Pull request by felix**
This requires the 'qs' library which does more than the Node 'querystring'
enabling us to spread the style array out nicely.

Updated the test as well.

### CODE REVIEW

**Comment by rayshan** [comment]
Thanks @felix, I've tested it and works as expected. Failed tests are only in node 0.8, probably ok. Can't really comment on the code style as I'm not familiar with the code base.

**Comment by felix** [comment]
Let me know if code style has to change. Also not sure about travis failures, let me know what I need to get them to work.

**Comment by moshen** [comment]
Probably should just remove node 0.8 from testing, quite old now.  @fabriziomoscon ?

**Comment by ShayDavidson** [comment]
Is the fork where this is fixed published in NPM? I'd really like to use this without having to wait for this to be merged.

**Comment by ShayDavidson** [comment]
What I actually meant to ask, (since I can reference that fork in my package.json), is when this is going to be merged, since without this static maps style are pretty broken

**Comment by ShayDavidson** [comment]
What I actually meant to ask, (since I can reference that fork in my package.json), is when this is going to be merged, since without this static maps style are pretty broken

**Comment by huei90** [comment]
This looks good :+1:

**Comment by fabriziomoscon** [comment]
I still haven't got a chance to test this work personally.

Although it looks like this PR changes the expected results for this test: https://github.com/felix/node-googlemaps/blob/86-single-style/test/unit/utils/parseStylesTest.js#L48

I understand `qs` helps with nesting of parameters, but because of the change in the test it is not possible to ensure this change won't break other users' code.

**Comment by felix** [comment]
Been a while since this pull request started. It seems the change to the parseStylesTest is necessary to test the whole point of this PR. If parseStyles is actually part of the public API then yes, it may break others' code, but it is broken anyway.

**Comment by fabriziomoscon** [comment]
Ok, I tested your changes and they look good.
Please amend these blocks to make them consistent with the new return type of the function
https://github.com/felix/node-googlemaps/blob/86-single-style/test/unit/utils/parseStylesTest.js#L30
https://github.com/moshen/node-googlemaps/blob/master/lib%2Futils%2FparseStyles.js#L2,L15

 and then it is good to be merged

**Comment by fabriziomoscon** [comment]
@felix @rayshan this is now published on npm under version 1.2.0

**Comment by rayshan** [comment]
:tada: thanks @felix @fabriziomoscon & team!

**Pull request merged**
