### PR TITLE
add place text-search api

### PR DESCRIPTION
**Pull request by jettcalleja**
added place text search api, to call: 

```
let gmAPI = new GoogleMapsAPI({ 
        key:    API_KEY,
        secure: true, // use https
    });

  gmApi.placeText({query: myAddress}, callback);

```

### CODE REVIEW

**Comment by fabriziomoscon** [comment]
Thank you for contributing!

Few comments:
- use `place-search-text` rather than `place-text` to be more specific and clear for the end user (we should also change the `place-search`
- a reference in the README.md about usage and google maps official documentation https://developers.google.com/places/web-service/search#TextSearchRequests
- some unit test
- at least one integration test

**Comment by jettcalleja** [comment]
thank you! will do that now.

**Comment by jettcalleja** [comment]
please check it now. thanks!

**Comment by fabriziomoscon** [comment]
published as npm `googlemaps@1.12.0`

**Pull request merged**
