### PR TITLE
Adding in ability to use traffic_model in directions and distance matrix

### PR DESCRIPTION
**Pull request by evansiroky**
- consolidated common code in directions and distance matrix
- added integration test for directions
- added unit tests for directions and distance

### CODE REVIEW

**Comment by fabriziomoscon** [comment]
@evansiroky nice work!
Very good idea to collect in a common place the travel utility function.
Just one suggestion from my side:
the expression `if (!commonValidation.valid) {` is `true` even when - because of bugs - `commonValidation.valid` is set to `null/undefined/0`. As a maintainer I need to keep the code as robust as possible.
Consider using try/catch and an exception inside the utility function to avoid this problem. 
Using `an exception would also allow you to remove the following:
```
var _err = function(err) {
   return { valid: false, error: err }
}
```
Throwing an exception in this case is safe because you are inside a synchronous call.
Alternatively if you don't like to use exceptions you could use something similar to `if (common.validation === false)` to make the code more robust.

Unless I am missing something about the above implementation, I would ask you to amend your PR according to my suggestion so that your code can be merged and published on `npm`.

**Comment by evansiroky** [comment]
I implemented your suggestion about throwing errors.  It looks cleaner now and is less code!

**Comment by fabriziomoscon** [comment]
very good.
I merged it and publish on `npm` for version `v1.1.3`.

Thank you very much for the contribution

**Comment by evansiroky** [comment]
You're welcome!

**Pull request merged**
